### ISSUE TITLE
Outline/highlight option doesn't work with graphics set to "Fabulous"

### ISSUE THREAD

**Issue by thexaero** [CloudG360/Survival-Building-Toolkit#7]
I could be wrong but I think `OutlineRendererMixin.renderTracedViewPath` is simply missing an `this.renderBuffers.bufferSource().endBatch(RenderType.lines())` call at the end. Or perhaps needs to be injected elsewhere, before Minecraft calls it. Discovered this because of a compatibility issue with my minimap mod. Although my mod should've definitely expected something like this, so I'll fix the compatibility on my end as well.

Tested on _2.2.0+1.20.1.fabric_

**Comment by squeeglii** [comment]
Replicated on 1.20.4

That fix didn't work sadly :( - I'll have a poke around over the next few days to see if that needs injecting at a different point or if the mixin needs moving.

Rendering is strange.

**Comment by squeeglii** [comment]
Turns out the mixin just needed moving. 

The vanilla handling of block outlines doesn't seem to end the batch itself so I've moved the injection point to just after that vanilla behaviour in the hopes that it'll just keep working. Let me know if there's any further compatibility issues with v2.2.1 :)

Patch will be published soonish.

**Comment by thexaero** [comment]
Thanks for the fix! 
Yeah, I'm not sure about the specifics of fabulous graphics. Perhaps it was too late to render lines there, so you had to move the code.
